title: "Create a ATP in Oracle Cloud Infrastructure"
description: "Create a ATP in Oracle Cloud Infrastructure"
schemaVersion: 1.1.0
version: "20200301"
locale: "en"

variableGroups:
  - title: "General Config"
    visible: false
    variables:
    - compartment_ocid
    - region
    - tenancy_ocid
    - autonomous_database_is_dedicated
    - autonomous_database_license_model
    - autonomous_database_db_workload

  - title: "Autonomous Transaction Processing Config"
    visible: true
    variables:
    - autonomous_database_db_name 
    - autonomous_database_display_name
    - autonomous_database_whitelisted_ips 
    - autonomous_database_version

variables:

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: "Compartment ID"
    description: "Compartment ID"
  
  region:
    type: oci:identity:region:name
    required: true
    title: "Region"
    description: "Region"

  tenancy_ocid:
    type: oci:identity:tenancy:id
    required: true
    title: "Tenancy OCID"
    description: "Please select the target tenancy"

  autonomous_database_db_name:
    type: string
    required: true
    default: "adbdb1"
    title: "ATP DB Name"
    description: "Input ATP DB Name"

  autonomous_database_display_name:
    type: string
    required: true
    default: "example_autonomous_database"
    title: "ATP Display Name"
    description: "Input ATP Display Name"

  autonomous_database_version:
    type: oci:database:autonomousdatabaseversion:id
    title: "ATP DB Version"
    description: "Select ATP DB version"
    required: true
    default: "19c"
    additionalProps:
      dbWorkload: "OLTP"
    dependsOn:
      compartmentId: ${compartment_ocid}

outputs:
  autonomous_database_admin_password:
    type: string
    title: "ATP Admin Password"
    displayText: "ATP Admin Password"
    visible: true
    sensitive: true

  autonomous_database_wallet_password:
    type: string
    title: "ATP Wallet Password"
    displayText: "ATP Wallet Password"
    visible: true
    sensitive: true